mergestat/mergestat-lite

- .github/workflows/test.yml
Just specifying "push" doesn't seem to trigger an actions run for PRs opened from forks, maybe this will?
> add pull_request to github actions file

- cmd/root.go
- pkg/gitqlite/gitqlite_test.go
This is a re-handling of #2 from @OutOfBrain. Thanks for the initial PR! I tried that code locally but was having some problems with local paths that seemed to be parsable by vcsurl AND where `remote.Kind == vcsurl.Git` (I didn't dig into why) but I believe this addresses more thoroughly. Also includes your fix in the test file, thanks!
> Resolve local repos

- pkg/gitqlite/gitqlite.go
Use a "shared" cache per repo on disk, which prevents issues when used as a library querying multiple repos at a time
> Open DB based on repo path

- README.md
When using only the image name in docker command, it fails with a `Unable to find image 'askgit:latest' locally`
Adding the owner to the docker image (as `augmentable/askgit`) solves the issue.
> When using only the image name in docker command, it fails

- pkg/gitqlite/gitqlite.go
- pkg/gitqlite/helpers_test.go
I've had difficulty splitting strings using the built-in sqlite str functions, this is a helper to make splitting strings in queries more succinct. The use case I have in mind, is when dealing with semver tag names such as `v1.2.3`, this makes it a little easier to pull out the components of a semver string (and therefore sort on it)
> loads a helper function for splitting strings

- cmd/root.go
- pkg/gitqlite/gitqlite_test.go
- pkg/gitqlite/helpers_test.go
Use the user's default ssh key when cloning via SSH. Should close #59
> SSH cloning

- pkg/ghqlite/pull_requests_vtab.go
- pkg/ghqlite/repos_vtab.go
fixes a bug to now allow queries like:
```
SELECT repo.*, pr.* FROM github_org_repos("augmentable-dev") repo, github_pull_requests("augmentable-dev", name) pr
```
> modification to how github table filter and best index works

- README.md
- cmd/export.go
- cmd/root.go
- pkg/askgit/askgit.go
- pkg/askgit/helpers_test.go
- pkg/gitqlite/git_branches.go
- pkg/gitqlite/git_files.go
- pkg/gitqlite/git_log.go
- pkg/gitqlite/git_log_cli.go
- pkg/gitqlite/git_stats.go
- pkg/gitqlite/git_tags.go
- pkg/gitqlite/gitqlite_test.go
Currently, something along the lines of:
```
askgit export my-db-file -e exported_commits,"SELECT * FROM commits" -e exported_branches,"SELECT * FROM branches"
```
Will create (or modify an existing) `my-db-file`, creating tables `exported_commits` and `exported_branches` as the corresponding query in the command.
Note that `commits` and `branches` already exist as tables, so exported tables need to have a new name (maybe this experience can be improved)
> Make it easier (possible) to export tables into a sqlite db

- pkg/ghqlite/pull_requests_vtab.go
some fields on a PR are not available when it is retrieved from a List call, this will issue a Get for a single PR if one of those columns is requested (and "cache" it for other columns in the same PR)
> a bit hacky, but retrieves "extra fields" from a PR when requested

- README.md
The suggested usage in the README did not work for me.
I was able to get it working as expected by repeating the `-e` flag in pairs.
This updates the README to reflect the usage which works.
> Update `export` usage in README

- README.md
Copied from here: https://pkg.go.dev/badge/?path=https%3A%2F%2Fgithub.com%2Faskgitdev%2Faskgit
> Use the "official" go reference badge

- cmd/root.go
- cmd/setup.go
- go.mod
- go.sum
- shared.go
- tables/internal/github/stargazers.go
- tables/internal/github/stargazers_count.go
- tables/internal/github/starred_repos.go
- tables/internal/github/utils.go
- tables/tables.go
My renamed names are just place holders. We can think of better ones.
> Start support for GitHub tables via GraphQL API `github_stargazers`, `github_starred_repos`, `github_stargazers_count`

- .github/workflows/release.yml
- .github/workflows/test.yml
This should begin to address what's been requested in #138 (thanks @wi1dcard for bringing it up) by building binaries for Mac and Linux in a GitHub action that runs when a release tag (`v*`) is pushed. Eventually, we can test releases for windows as well.
It may be worth adding an installation script somewhere at some point, to handle downloading the latest release and dropping it somewhere in a user's path, but this should be a good enough start to allow users to get a prebuilt binary (statically linked to libgit2) vs requiring them to build themselves.
Closes #138
> GitHub action to push macos and linux binaries on new `v*` releases

- extensions/internal/sourcegraph/sourcegraph_search.go
change matches to an array so return can unpack correctly
> Fix commitSearchResults struct

- cmd/setup.go
- pkg/locator/locator.go
Simple for now, detects if a repo path starts with `ssh://` (and then strips it out) and uses the go-git ssh auth method to clone to a temporary directory
> implement an SSH repo locator

- cmd/setup.go
- extensions/internal/git/git_test.go
- extensions/internal/git/native/native_test.go
- pkg/locator/locator.go
- shared.go
If it's set by the user. Makes it a bit easier to work with private repos via a `GITHUB_TOKEN`, which may already be supplied for GitHub API tables.
> feat: use `GITHUB_TOKEN` env for cloning `https` repos

- cmd/root.go
- cmd/setup.go
- extensions/internal/git/clone.go
- extensions/internal/git/git.go
- pkg/locator/locator.go
- shared.go
by default (if no `--clone-dir` flag is set) `mergestat` will just create a temporary directory for cloning the repo before executing a query
> feat: allow user to set directory where repos are cloned to

- cmd/root.go
- go.mod
- pkg/display/display.go
- pkg/display/display_test.go
and make the `json` format output a JSON array of objects (instead of line-delimited json objects)
Closes #230
> feat: rename current `json` output format to `ndjson`

- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
- go.mod
- go.sum
Were having some build issues in `macos` on GitHub actions, they were resolved when upgrading to Go `1.17`. This updates our CI to also include runs on `macos` so we shouldn't encounter "surprise" build issues at release again.
> Add MacOS environment to CI and bump to Go `1.17`

- cmd/root.go
- cmd/summary.go
- cmd/summary/summary.go
- go.mod
- go.sum
> feat: improvements to `summary` command

- cmd/export.go
- cmd/pgsync.go
- cmd/root.go
This PR adds two features, which can be useful in conjunction:
1. Add a `--db` or `-d` flag to the root command (when executing SQL) to specify a sqlite database file to mount (instead of using an in-memory one).
2. Add an `--append` flag to the `export` command, which will attempt to INSERT rows into a table if it exists already (and if the query schema matches)
These two flags can be useful together in scripts for larger-scale data collection. For instance, `mergestat export mydb.sqlite --append -e combined_commits -e "SELECT * FROM commits"` maybe be run multiple times for different repositories to collect the commit history of multiple codebases in one table.
Then `mergestat --db mydb.sqlite "SELECT * FROM combined_commits"` may be used to run queries against the "combined" table in …
> feat: allow specifying a sqlite db to mount, add `--append` mode to `export` command

- cmd/summary.go
- cmd/summary/summary.go
Adds date filters to the `summary` subcommand (`--start` and `--end`) to let users specify a date range of commits to consider (using the `author_when` column).
The expected format is `YYYY-MM-DD`. Can also be a SQLite "[date modifier](https://www.sqlite.org/lang_datefunc.html)" relative to `now`. So `--start "-30 days"` will only consider commits authors in the last 30 days.
Also adds a `--json` flag, which outputs the `summary` tables but as a JSON object.
> feat: add date filtering and `--json` output to the `summary` sub command

- cmd/root.go
- cmd/setup.go
- pkg/locator/locator.go
- shared.go
> feat: add support for `GIT_SSL_NO_VERIFY` when cloning repos

- extensions/internal/git/log.go
when a query uses the `hash` filter on the log table
> fix: address issue with mailmap parsing not occurring

- cmd/root.go
- pkg/display/display.go
- pkg/display/display_test.go
Same output as `csv` and `tsv`, just don't include the column names in the header. #248
> feat: implement `csv-noheader` and `tsv-noheader` output formats

- .github/workflows/release.yml
- .github/workflows/test.yml
- .gitmodules
- .vscode/settings.json
- Dockerfile
- Makefile
- go.mod
- go.sum
Uses the instructions [here](https://github.com/libgit2/git2go/#main-branch-or-vendored-static-linking) (`main` branch, or vendored static linking) to vendor `libgit2` and `git2go` into this repo.
We're encountering an [issue](https://github.com/mergestat/homebrew-mergestat/issues/21) with homebrew installations when the upstream `libgit2` gets an update and we haven't upgraded `mergestat` to support the new `libgit2` version. Homebrew doesn't seem to allow us to pin to a particular version, so installations begin breaking.
I see two possible solutions:
1. Vendor `libgit2` (and `git2go`) into this repo so that builds will statically link it, no need to depend on a system `libgit2` (what this PR does)
2. Update the `homebrew` installation to just copy a pre-built binary
Or maybe both...
> feat: vendor `libgit2` (via `git2go`)

- extensions/internal/github/branches.go
- extensions/internal/github/github.go
- extensions/internal/github/issues_comments.go
- extensions/internal/github/org_repos.go
- extensions/internal/github/pr_comments.go
- extensions/internal/github/pr_commits.go
- extensions/internal/github/repo.go
- extensions/internal/github/repo_branch_protection.go
- extensions/internal/github/repo_commits.go
- extensions/internal/github/repo_file_content.go
- extensions/internal/github/repo_issues.go
- extensions/internal/github/repo_prs.go
- extensions/internal/github/stargazer_count.go
- extensions/internal/github/stargazers.go
- extensions/internal/github/starred_repos.go
- extensions/internal/github/user_info.go
- extensions/internal/github/user_repos.go
- extensions/internal/github/utils.go
- extensions/options/github.go
- extensions/options/options.go
allow library consumers to supply their own github rate limit handler
> fix: refactor github rate limit handler to be settable

- extensions/internal/github/repo_prs.go
this enables an "early exit" optimization which will tell the `vtab` library to avoid a full table scan in certain cases when a WHERE and ORDER BY clause are used
> fix: add constraints for `github_repo_prs` table

- extensions/internal/github/fixtures/TestOrgAuditLog.yaml
- extensions/internal/github/github.go
- extensions/internal/github/org_audit_log.go
- extensions/internal/github/org_audit_log_test.go
Builds on previous work done by @Vialeon, adds basic support for querying the GitHub audit log via API (only available for enterprise plans).
Closes #294
> feat: implement a `github_org_audit_log` table

- extensions/internal/github/org_audit_log.go
- extensions/internal/github/org_audit_log_test.go
Adds a new column `actor_location` to the `github_org_audit_log`
> feat: add `actor_location` column to the `github_org_audit_log` table

- renovate.json
Hopefully to fix issues in the renovate PRs
> fix: try adding `gomodMassage` to renovate config

- Makefile
- extensions/internal/git/log_test.go
- extensions/internal/git/native/blame_test.go
- extensions/internal/git/native/files_test.go
- extensions/internal/git/native/stats_test.go
- extensions/internal/git/refs_func_test.go
- extensions/internal/git/refs_test.go
as a fixture repo. Now that the repo has been renamed, we should use `github.com/mergestat/mergestat-lite` to look for the SHAs or related objects we expect.
> fix: failing test cases that uses `github.com/mergestat/mergestat`

- extensions/internal/git/native/blame.go
- extensions/internal/git/native/files.go
- extensions/internal/git/native/stats.go
- go.mod
- go.sum
- scripts/install_libgit2.sh
To `libgit2 v1.5` and `git2go v34`
> chore: upgrade `libgit2` and `git2go` versions

- extensions/internal/git/native/stats.go
Adds `old_file_mode` and `new_file_mode` columns to `stats` table. These can be:
- `unknown`
- `none`
- `regular_file`
- `symbolic_link`
- `git_link`
This matches what was done here: https://github.com/mergestat/mergestat/pull/321
> feat: add file mode columns to `stats` table-valued-function

- cmd/summarize/commits/commits.go
Before change:
```
devzero@ngvzugqq mergestat-lite (main) $ make .build/mergestat && .build/mergestat -r ../services/ summarize commits --verbose
-- building .build/mergestat
-- built .build/mergestat
May 15 18:03:02 INF opening repo path=../services/
May 15 18:03:48 ERR sql: Scan error on column index 1, name "author_email": converting NULL to string is unsupported
```
After change:
```
devzero@ngvzugqq mergestat-lite (main) $ make .build/mergestat && .build/mergestat -r ../services/ summarize commits --verbose
-- building .build/mergestat
-- built .build/mergestat
May 15 18:06:50 INF opening repo path=../services/
wunderwuzzi23         88        3.49%      49        27,351      14,622      3 years ago (2021-05-05)   
```
> commit summary fails on 'author_email' being NULL

- go.mod
- go.sum
Latest builds of the standalone SQLite extension seemed unable to `.load` into SQLite. This PR just points to a less recent version of `go.riyazali.net/sqlite` (the last sha used that doesn't have the issue)
> fix: revert to last known working version of `go.riyazali.net/sqlite`
