Dockerfile
README.md

This PR adds a multi-stage Dockerfile for building the project as a docker container

feat: add Dockerfile and instructions to README

---

pkg/gitqlite/git_log.go
pkg/gitqlite/git_tree.go

i.e. with `git init` just having been run. Addresses #6 @youngminz

handle repos with no commits without panic-ing

---

pkg/gitlog/parse.go
pkg/gitqlite/git_log_cli.go

- move to a new `gitlog` package
- a bit of renaming

Git log CLI edits

---

README.md

capitalize key words in the final example for consistency

---

.github/workflows/test.yml

uploads coverage report to codecov.io

upload coverage after running tests

---

.github/workflows/test.yml
.gitignore
Makefile
cmd/root.go
go.mod
go.sum
pkg/gitqlite/git_branches.go
pkg/gitqlite/git_log_cli.go
pkg/gitqlite/git_tags.go
pkg/gitqlite/gitqlite.go
pkg/gitqlite/gitqlite_test.go

Tags table is working. For branches need to figure out how to pull all branches from a remote

V tables for tags and all branches

---

README.md

add a note about the docker image on docker hub to README

---

pkg/gitqlite/git_branches.go
pkg/gitqlite/git_log.go
pkg/gitqlite/git_log_cli.go
pkg/gitqlite/git_ref.go
pkg/gitqlite/git_tags.go
pkg/gitqlite/git_tree.go

- remove the index and eof fields from most cursors (unnecessary)
- move the cursor initialization into `Filter` where it belongs, addresses some weird bugs with self-joins not working

Cleaning up the virtual table implementations

---

README.md

A bit of rewording in the README

---

pkg/gitlog/parse.go
pkg/gitlog/parse_test.go
pkg/gitqlite/git_log.go
pkg/gitqlite/git_log_cli.go

Implements an iterator for parsing `git log` results. Also fixes up some stat calculations

Git CLI Iterator

---

Dockerfile
Makefile
README.md
askgit.go
cmd/root.go
go.mod
go.sum
pkg/gitqlite/git_log_cli.go

Renames this project and the command to `askgit`. `gitqlite` remains the name of a subpackage for the git sqlite virtual table implementation

rename this project to `askgit`

---

Dockerfile

Should (hopefully) address performance issue raised in #46

include git cli in docker image

---

pkg/gitqlite/gitqlite.go

possible fix for special characters

---

Makefile
README.md

Update xbuild step and add brew installation instructions

---

pkg/gitqlite/git_file_iter.go
pkg/gitqlite/git_files.go
pkg/gitqlite/git_files_test.go
pkg/gitqlite/git_log.go
pkg/gitqlite/git_log_test.go

For commits by id and files by commit_ids

Starts some "index" implementations

---

README.md
cmd/root.go
pkg/tui/conf.go
pkg/tui/helpers.go
pkg/tui/keybind.go
pkg/tui/tui.go

Rebased and slightly updated version of #54

Preconfigured queries updates

---

pkg/tui/conf.go

Addresses #42 but in a different way, building off the "preset queries" functionality currently available. This will be further documented/improved in coming PRs

adds a preset query called "tables" that lists available tables

---

pkg/gitqlite/git_stats.go

Much cleaner way to calculate stats

git stats table w/o string parsing. Using callbacks

---

.vscode/settings.json
pkg/gitlog/parse_test.go
pkg/gitqlite/git_stats.go
pkg/gitqlite/git_stats_iter.go
pkg/gitqlite/git_stats_test.go

Changes to stats implementation

---

README.md

update example query in README to use stats table

---

pkg/ghqlite/pull_requests_vtab.go

if a datetime is a zero value, return null

---

go.mod
go.sum
pkg/askgit/display.go
pkg/askgit/display_test.go

Cleaner table output edits

---

cmd/export.go
cmd/root.go

clear the tmp directory after the command, not the helper function

Fix bug when specifying remote repos

---

pkg/askgit/askgit.go

use a driver connector instead of a string

change how driver is setup

---

pkg/gitqlite/blame.go
pkg/gitqlite/blame_iter.go
pkg/gitqlite/blame_test.go

some more changes to the blame table

Blame updates updates

---

pkg/askgit/display.go

as discussed https://github.com/mattn/go-sqlite3/issues/902

handle the rows.Err() as well

---

pkg/gitqlite/blame.go
pkg/gitqlite/blame_iter.go

My attempt at simplifying some of the iterator...passes the tests but to be honest not sure if it works as expected/should

some refactoring to the blame iterator and table

---

cmd/root.go
pkg/askgit/display.go
pkg/askgit/display_test.go
pkg/tui/keybind.go
pkg/tui/tui.go

add a flag to allow full output in tui. Also make a few quality of life changes. Add page right,left,up,down

No cutoff in interactive mode

---

README.md

fixed function name in header

---

README.md
extensions/internal/github/fixtures/TestRepoFileContent.yaml
extensions/internal/github/fixtures/TestRepoFileContentMultiArg.yaml
extensions/internal/github/github.go
extensions/internal/github/repo_file_content.go
extensions/internal/github/repo_file_content_test.go

Looks up the contents of a file in a GitHub repo, via the v4 API

implement `github_repo_file_content ` GitHub scalar func

---

cmd/export.go
cmd/root.go

Looks a bit nicer on the console (red+bold output)

use the zerolog logger to report errors

---

README.md
extensions/internal/helpers/grep.go
extensions/internal/helpers/grep_test.go
extensions/internal/helpers/helpers.go

Minor fixes and renames, also makes it a regex search instead of string match

Some updates to `grep` table

---

README.md
extensions/internal/helpers/grep.go
extensions/internal/helpers/grep_test.go
extensions/internal/helpers/helpers.go

A table valued function that searches a string for a search term and returns each result as a row with the associated line number

feat: Grep table valued function

---

README.md
extensions/internal/github/fixtures/TestIssueComments.yaml
extensions/internal/github/github.go
extensions/internal/github/github_issues_comments.go
extensions/internal/github/github_issues_comments_test.go

table valued function that pulls each comment on all issues in a repo

Feat: table GitHub issues comments

---

README.md
extensions/internal/github/fixtures/TestUserInfo.yaml
extensions/internal/github/github.go
extensions/internal/github/github_user_info.go
extensions/internal/github/github_user_info_test.go

Some tweaks to the wording, naming and README docs

fix: GitHub user info edits

---

README.md
extensions/internal/github/fixtures/TestUserInfo.yaml
extensions/internal/github/github.go
extensions/internal/github/github_user_info.go
extensions/internal/github/github_user_info_test.go

A scalar function that, given a login, returns user information associated with that login

Feat: Scalar function to pull GitHub user info

---

extensions/internal/github/github_issues_comments.go
extensions/internal/github/github_pr_comments.go

of `github_issue_comments` and `github_pr_comments` needed to be made consistent

fix: date formatting on `created_at` and `updated_at` columns

---

extensions/internal/github/fixtures/TestBranches.yaml
extensions/internal/github/github.go
extensions/internal/github/github_branches.go
extensions/internal/github/github_branches_test.go

github branches table that returns branch information from a github repository
Usage
`Select * from github_repo_branches('mergestat','mergestat')`
`Select * from github_repo_branches('mergestat/mergestat')`
Closing #219

feat: GitHub branches table

---

extensions/extensions.go
extensions/options/options.go

allows for _excluding_ git functionality

feat: option to _exclude_ git functionality, when used as a library

---

extensions/internal/github/fixtures/TestPRCommits.yaml
extensions/internal/github/github_pr_commits.go
extensions/internal/github/github_pr_commits_test.go

- fix some typos
- add some columns
- add test fixtures

fix: some updates to the `github_repo_pr_commits` implementation

---

extensions/internal/github/fixtures/TestRepoCommits.yaml
extensions/internal/github/github.go
extensions/internal/github/github_repo_commits.go
extensions/internal/github/github_repo_commits_test.go

Feat: GitHub repo commits table

---

extensions/internal/git/native/blame.go
extensions/internal/git/native/files.go
extensions/internal/git/native/stats.go

fix: tweak error messages, `rev` -> `revision`

---

cmd/export.go
cmd/root.go
cmd/serve.go

Will need to document in the docs site.

feat: start a `service` mode implementation that runs a local HTTP API

---

extensions/internal/helpers/approx_duration.go
extensions/internal/helpers/approx_duration_test.go
extensions/internal/helpers/helpers.go
extensions/internal/helpers/timediff.go
extensions/internal/helpers/timediff_test.go

fix up some of the error paths as well (add early returns)

fix: rename scalar funs to `time_diff` and `approx_dur`

---

extensions/internal/helpers/helpers.go
extensions/internal/helpers/print_duration.go
extensions/internal/helpers/print_duration_test.go
extensions/internal/helpers/timediff.go
extensions/internal/helpers/timediff_test.go

scalar functions to pretty print datetimes and durations

feat: time formatting sqlite print functions

---

extensions/internal/github/branches.go
extensions/internal/github/github.go
extensions/internal/github/issues_comments.go
extensions/internal/github/org_repos.go
extensions/internal/github/pr_comments.go
extensions/internal/github/pr_commits.go
extensions/internal/github/repo.go
extensions/internal/github/repo_branch_protection.go
extensions/internal/github/repo_commits.go
extensions/internal/github/repo_file_content.go
extensions/internal/github/repo_issues.go
extensions/internal/github/repo_prs.go
extensions/internal/github/stargazer_count.go
extensions/internal/github/stargazers.go
extensions/internal/github/starred_repos.go
extensions/internal/github/user_info.go
extensions/internal/github/user_repos.go
extensions/internal/github/utils.go
extensions/options/options.go

to allow a user to run a function *after* every call to the GitHub API

feat: add GitHub post request hook

---

pkg/locator/locator.go

to address an issue with concurrent map access, when used across multiple go routines

fix: use a `sync.Map` instead of a plain map in the `CachedLocator`

---

cmd/root.go
cmd/serve.go
extensions/internal/enry/enry_detect_language_test.go
extensions/internal/enry/enry_is_binary_test.go
extensions/internal/git/native/files_test.go
extensions/internal/golang/go_mod_to_json_test.go
extensions/internal/npm/npm.go
pkg/locator/locator.go

Fix various lint issues - mostly update to standard library package imports

chore: update some lint issues (deprecated std lib packages)
